<?php
/**
 * Plugin Name: #Donation with UPI
 * Plugin URI: https://haysky.com/
 * Description: This plugin code is generated by Haysky Code Generator.
 * Version: 1.0.0
 * Author: Haysky
 * Author URI: https://haysky.com/
 * License: GPLv2 or later
  */
// $wpdb->show_errors(); $wpdb->print_error();
error_reporting(E_ERROR | E_PARSE);

add_action('admin_menu' , function(){
    add_menu_page('Donation Options','Donation Options','manage_options', 'donation_options_admin', 'donation_options_ium', 'dashicons-admin-users','2');
});

function donation_options_ium(){ include 'donation_options.php'; }


add_shortcode('donation_qr',function(){ include 'donation_qr.php'; });